version: '3'
services:
  vote-api:
    container_name: docker-vote-api
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '8000:8080'
    links:
      - vote-mongo
  vote-mongo:
    container_name: vote-mongo
    image: mongo
    ports:
      - '27017:27017'
